server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abimaelrsergio/2024-config-server
          #username: abimael
          #password: abimael
          search-paths:
          - 'greeting-service*'
